### ISSUE TITLE
3.0.0-nightly: Token Simulation turns on when typing 'T' in a label

### ISSUE THREAD

**Issue by falko** [bpmn-io/bpmn-js-token-simulation-plugin#14] opened 2019-02-09 15:23 UTC
In today's nightly build of Camunda Modeler 3.0.0 the Token Simulation Plugin turns on when typing 'T' in a label.

**Comment by nikku** [comment] 2019-02-12 09:54
Potential Camunda Modeler `v3.x issue`.

**Comment by pinussilvestrus** [comment] 2019-02-26 11:36
This is indeed a regression of the latest release since we already fixed it once before (cf. https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/commit/d480ff32ea6e500c28b6bcccfa6ba1502a4efedb).

**Comment by pinussilvestrus** [comment] 2019-02-26 13:36
Hi @falko, we just merged [a commit](https://github.com/camunda/camunda-modeler/pull/1275/commits/9cefbad0f6b461a3aa2c17d7554bbbb35c0067df) inside the Camunda Modeler which should fix it. Maybe you can try out with the next nightly and verify that the bug doesn't appear again?

**Comment by nikku** [comment] 2019-02-26 15:21
Closed via https://github.com/camunda/camunda-modeler/issues/1193.

**Closed by nikku** 2019-02-26 15:21 UTC
Labels: bug, ready
