### ISSUE TITLE
Selected sequence flow @ gateway not indicated (Modeler v 4.8.1)

### ISSUE THREAD

**Issue by joehm** [bpmn-io/bpmn-js-token-simulation-plugin#37] opened 2021-07-20 07:13 UTC
The toggle button "Set Sequence Flow" at gateways used to indicate the selected sequence flow by showing the disabled flow as light gray. This is no longer the case wit Modeler v. 4.8.1 (while the actual functionality works).

Tested with: 
Modeler 4.8.1
MacOS Big Sur 11.2

**Comment by nikku** [comment] 2021-07-20 07:21
Friendly reminder: Please use our existing issue template when reporting bugs.

In this case, it is a duplicate of https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/31. 

Fixed with Camunda Modeler v4.9 release, cf. https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/31#issuecomment-845148488.

**Closed by nikku** 2021-07-20 07:21 UTC
Labels: bug
