### ISSUE TITLE
Set sequence flow doesn't make gray the deselected path on Linux.

### ISSUE THREAD

**Issue by ddozza** [bpmn-io/bpmn-js-token-simulation-plugin#35] opened 2021-06-23 14:41 UTC
It seems that under Linux I cannot distinguish selected from deselected path.
- Camunda Modeler 4.8.1 
- Linux Mint 20.1 Mate
![Peek 2021-06-23 16-33](https://user-images.githubusercontent.com/2803752/123116994-a91aca00-d441-11eb-85ab-67ec7d52aae7.gif)

**Comment by nikku** [comment] 2021-06-23 16:27
Duplicate of https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/31. Fixed in next Camunda Modeler release, cf. https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/31#issuecomment-845148488.

**Closed by nikku** 2021-06-23 16:27 UTC
Labels: bug
