### ISSUE TITLE
Active sequence flow after XOR is not highlighted

### ISSUE THREAD

**Issue by McAlm** [bpmn-io/bpmn-js-token-simulation-plugin#36] opened 2021-07-02 07:40 UTC
In previous versions (and in https://bpmn-io.github.io/bpmn-js-token-simulation/modeler.html?e=1) the choosen outgoing sequence flow after an XOR is highlighted (or to be more precise: the inactive ones are rendered as disabled). This does not work in Camunda Modeler anymore.
All sequence flows look alike, that makes it difficult to control the flow during the simulation.

__Expected Behavior__
The activated outgoing sequence flows should be visibly highlighted.

__Environment__

- OS:  Mac OS BigSur
- Camunda Modeler 4.8.1

**Comment by nikku** [comment] 2021-07-05 07:48
Duplicate of https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/31.

**Closed by nikku** 2021-07-05 07:48 UTC
Labels: bug, duplicate
