### ISSUE TITLE
Can't toggle in Modeler 4.11

### ISSUE THREAD

**Issue by HarryWu-CHN** [bpmn-io/bpmn-js-token-simulation-plugin#52] opened 2022-03-04 07:42 UTC
I follow the README to put the project in plugins, but it can't be toggled.

```
toggleTokenSimulation is not a registered action
    at o (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:257:9)
    at error (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:167:10)
    at trigger (webpack:///src/app/tabs/cloud-bpmn/BpmnEditor.js:529:40)
    at triggerAction (webpack:///src/app/tabs/MultiSheetTab.js:269:18)
    at triggerAction (webpack:///src/app/tabs/EditorTab.js:36:33)
    at triggerAction (webpack:///src/app/App.js:1782:15)
    at fn (webpack:///src/app/App.js:2250:19)
    at file:///D:/%E8%AF%BE%E4%BB%B6/%E6%AF%95%E8%AE%BE/camunda/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/bundle.js:73:148465
    at exec (webpack:///src/app/AppParent.js:76:11) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
```
What should I do?

Modeler Version 4.11.1
Window 10

**Comment by pinussilvestrus** [comment] 2022-03-04 07:47
Thanks for reporting. According to your logs, you are working in a Camunda Cloud BPMN file. Note that plugins are not supported for those in Camunda Modeler v4.x.

Cf. https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/48

We plan to support plugins for Camunda Cloud BPMN files in Camunda Modeler v5, though.

I'll close this issue since it's a duplicate of https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/48

**Closed by pinussilvestrus** 2022-03-04 07:47 UTC
Labels: bug
