### ISSUE TITLE
Plugin broken when working with camunda modeler 4.11.1

### ISSUE THREAD

**Issue by Nelly1313** [bpmn-io/bpmn-js-token-simulation-plugin#40] opened 2021-11-19 07:22 UTC
Starting the token simulator while working with camunda modeler 4.11.1 causes this exception:

A DOM element reference is required
    at new (webpack:///node_modules/min-dom/dist/index.esm.js:75:0)
    at classes (webpack:///node_modules/min-dom/dist/index.esm.js:63:0)
    at file:///C:/Users/LENOVO/Desktop/camunda-modeler-4.11.1-win-x64/resources/plugins/bpmn-js-token-simulation-plugin/client/client.bundle.js:123:7
    at file:///C:/Users/LENOVO/Desktop/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/2.2.js:1:50766
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:371:33)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:352:23)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:313:23)
    at ToggleMode../node_modules/bpmn-js-token-simulation/lib/features/toggle-mode/modeler/ToggleMode.js.ToggleMode.toggleMode (webpack:///node_modules/bpmn-js-token-simulation/lib/features/toggle-mode/modeler/ToggleMode.js:63:0) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]

**Comment by nikku** [comment] 2021-11-19 08:32
Thanks for opening this issue.

Please use our existing template and add more required data:

* When did it break
* When did it work
* OS, installed plug-ins, ...

**Comment by Nelly1313** [comment] 2021-11-19 08:35
The simulator did not work directly from the beginning after installing camunda modeler 4.11.1 and adding the newest version from the plugin loaded from github. The exception occured immediatly after starting it.

**Comment by nikku** [comment] 2021-11-24 10:16
Closing this one as won't fix.

I cannot reproduce your issue with a clean Camunda Modeler @ 4.11.1 + the latest version of this plug-in.

**Closed by nikku** 2021-11-24 10:16 UTC
Labels: bug, help wanted

**Comment by Nelly1313** [comment] 2021-11-26 12:06
I tried removing Camunda Modeler v4.11.1 and reloaded a fresh version as well as the newest version of the token simulator plugin and as soon as activating the plugin the error is reocurring. I don't know why you can't reproduce the error but it's still not working.


![Error token simulator](https://user-images.githubusercontent.com/94673055/143578371-b9c002d8-dc2e-4efd-9559-4906420662f6.PNG)

**Comment by nikku** [comment] 2021-11-26 12:22
Did you consider updating the plug-in?

**Comment by Nelly1313** [comment] 2021-11-26 12:24
I pulled the most recent version and tried updating the libraries via npm update but did not manage to remove the error.

**Comment by pinussilvestrus** [comment] 2021-11-26 12:49
I can not reproduce this on Mac as well. Do you have any other plugins installed?

**Comment by Nelly1313** [comment] 2021-11-26 12:53
I've had the linter plugin as well as the token simulator installed and was working on writing own rules for the linter so I assumed i broke something while doing this, but after removing all plugins as well as the Camunda Modeler and loading a fresh version with the fresh plugin, the error still occurred.

**Comment by barmac** [comment] 2021-11-26 12:54
Does it happen with any diagram or just the one you tested? If the former is true, please share the diagram.

**Comment by Nelly1313** [comment] 2021-11-26 12:57
It happened with any diagram i used for testing and no matter if the start or the end event miss, no error is displayed even if it is registered.

**Comment by barmac** [comment] 2021-11-26 13:09
I can't reproduce it on Mac.

**Comment by Nelly1313** [comment] 2021-11-26 18:36
I'm using a windows computer.

**Comment by Nelly1313** [comment] 2021-12-02 09:11
I tried installing Camunda Modeler v4.10 on another Windows computer and tried the token simulator plugin on this computer. The same exception appears on the other computer as well.

**Comment by pinussilvestrus** [comment] 2021-12-02 09:12
@philippfromme can you maybe try to reproduce this problem?
